-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 16:27:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ZooManagementDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS ZooMngemntDB;
CREATE DATABASE IF NOT EXISTS ZooMngemntDB;
USE ZooMngemntDB;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zoo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Zoo` ;

CREATE TABLE IF NOT EXISTS `Zoo` (
  `zoo_id` INT UNSIGNED NOT NULL,
  `zoo_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`zoo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Head Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Head Director` ;

CREATE TABLE IF NOT EXISTS `Head Director` (
  `zoo` INT UNSIGNED NOT NULL,
  `director_id` INT UNSIGNED NOT NULL,
  `age` TINYINT(3) UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`director_id`),
  INDEX `FK_ZOO_idx` (`zoo` ASC) VISIBLE,
  CONSTRAINT `FK_ZOO`
    FOREIGN KEY (`zoo`)
    REFERENCES `Zoo` (`zoo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinarian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinarian` ;

CREATE TABLE IF NOT EXISTS `Veterinarian` (
  `vet_id` INT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exhibit Curator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exhibit Curator` ;

CREATE TABLE IF NOT EXISTS `Exhibit Curator` (
  `curator_id` INT UNSIGNED NOT NULL,
  `curator_name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) NOT NULL,
  PRIMARY KEY (`curator_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Keeper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Keeper` ;

CREATE TABLE IF NOT EXISTS `Keeper` (
  `keeper_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  PRIMARY KEY (`keeper_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Finance Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Finance Director` ;

CREATE TABLE IF NOT EXISTS `Finance Director` (
  `director_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`director_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Visitor` ;

CREATE TABLE IF NOT EXISTS `Visitor` (
  `user` INT UNSIGNED NOT NULL,
  `zoo` INT UNSIGNED NOT NULL,
  `visitor_id` INT UNSIGNED NOT NULL,
  `age` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`visitor_id`),
  INDEX `user_idx` (`user` ASC) VISIBLE,
  INDEX `zoo_idx` (`zoo` ASC) VISIBLE,
  CONSTRAINT `FK_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zoo`
    FOREIGN KEY (`zoo`)
    REFERENCES `Zoo` (`zoo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ticket` ;

CREATE TABLE IF NOT EXISTS `Ticket` (
  `ticket_id` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ticket_id`),
  UNIQUE INDEX `ticket_id_UNIQUE` (`ticket_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visitor Service Center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Visitor Service Center` ;

CREATE TABLE IF NOT EXISTS `Visitor Service Center` (
  `center_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`center_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visitor Service worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Visitor Service worker` ;

CREATE TABLE IF NOT EXISTS `Visitor Service worker` (
  `Visitor_Service_Center` INT UNSIGNED NOT NULL,
  `worker_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`worker_id`),
  INDEX `Visitor_Service_Center_idx` (`Visitor_Service_Center` ASC) VISIBLE,
  CONSTRAINT `Visitor_Service_Center`
    FOREIGN KEY (`Visitor_Service_Center`)
    REFERENCES `Visitor Service Center` (`center_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Animal` ;

CREATE TABLE IF NOT EXISTS `Animal` (
  `animal_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `species` VARCHAR(45) NULL,
  `health` MEDIUMTEXT NULL,
  PRIMARY KEY (`animal_id`),
  UNIQUE INDEX `animal_id_UNIQUE` (`animal_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exhibit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exhibit` ;

CREATE TABLE IF NOT EXISTS `Exhibit` (
  `animal` INT UNSIGNED NULL,
  `exhibit_id` INT UNSIGNED NOT NULL,
  `fk_zoo` INT UNSIGNED NOT NULL,
  `exhibit_curator` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`exhibit_id`),
  INDEX `animal_idx` (`animal` ASC) VISIBLE,
  INDEX `zoo_idx` (`fk_zoo` ASC) VISIBLE,
  INDEX `exhibit_curator_idx` (`exhibit_curator` ASC) VISIBLE,
  CONSTRAINT `animal`
    FOREIGN KEY (`animal`)
    REFERENCES `Animal` (`animal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKey_zoo`
    FOREIGN KEY (`fk_zoo`)
    REFERENCES `Zoo` (`zoo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exhibit_curator`
    FOREIGN KEY (`exhibit_curator`)
    REFERENCES `Exhibit Curator` (`curator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales` ;

CREATE TABLE IF NOT EXISTS `Sales` (
  `sales_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `quantity_sold` INT UNSIGNED NOT NULL,
  `total_money_made` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`sales_id`),
  UNIQUE INDEX `sales_id_UNIQUE` (`sales_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Food Choice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Food Choice` ;

CREATE TABLE IF NOT EXISTS `Food Choice` (
  `food_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enrichment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Enrichment` ;

CREATE TABLE IF NOT EXISTS `Enrichment` (
  `enrichment_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`enrichment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toys` ;

CREATE TABLE IF NOT EXISTS `Toys` (
  `toy_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`toy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `user` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `Fkey_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inventory` ;

CREATE TABLE IF NOT EXISTS `Inventory` (
  `inventory_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`inventory_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
